"""Symphony adapter: bridge between Symphony orchestration and report pipeline.

This module provides:
- SymphonyPlanRequest: input to request a plan from Symphony
- SymphonyExecutionTrace: record of plan vs actual execution
- generate_symphony_plan(): call Symphony API (when available)
- validate_plan(): check plan against policy validator

Status: The adapter schema is defined but actual Symphony API calls
require a running JiuwenSwarm instance with score artifacts available.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List

from jiuwenswarm.quant.reporting.submission_contract import get_contract


@dataclass
class SymphonyPlanRequest:
    """Request to Symphony for report workflow planning."""
    query: str
    candidate_skill_ids: List[str] = field(default_factory=list)
    mode: str = "fast"  # "fast" | "thorough" | "creative"

    # Context passed to Symphony for better planning
    contract_company_count: int = field(
        default_factory=lambda: get_contract().n_companies
    )
    data_available: bool = True
    coverage_ok: bool = True


@dataclass
class PlanStep:
    """One step in a Symphony-generated plan."""
    step_id: str
    skill_name: str
    description: str
    depends_on: List[str] = field(default_factory=list)
    expected_outputs: List[str] = field(default_factory=list)


@dataclass
class SymphonyPlan:
    """A plan generated by Symphony for report workflow execution."""
    plan_id: str
    query: str
    generated_at: datetime
    steps: List[PlanStep] = field(default_factory=list)
    mermaid_diagram: str = ""
    raw_response: Dict[str, Any] = field(default_factory=dict)
    source: str = "symphony_api"  # "symphony_api" | "static_fallback" | "manual"


@dataclass
class PlanValidationResult:
    """Result of validating a Symphony plan against policy."""
    valid: bool
    blockers: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    missing_required_skills: List[str] = field(default_factory=list)
    ordering_violations: List[str] = field(default_factory=list)


@dataclass
class SymphonyExecutionTrace:
    """Record of actual execution vs the Symphony plan."""
    plan: SymphonyPlan
    execution_id: str
    started_at: datetime | None = None
    finished_at: datetime | None = None
    step_results: Dict[str, Dict[str, Any]] = field(default_factory=dict)
    deviations: List[str] = field(default_factory=list)
    success: bool = False


# ---- Policy Validator ----

_REQUIRED_SKILL_ORDER = [
    "fetch_data",
    "compute_factors",
    "alpha_view",
    "risk_evidence_view",
    "select_stocks",
    "allocate_positions",
    "run_backtest",
    "generate_report",
]

_REQUIRED_SKILLS = set(_REQUIRED_SKILL_ORDER)


def validate_quant_plan(plan: SymphonyPlan) -> PlanValidationResult:
    """Validate a Symphony-generated plan for the quant workflow.

    Checks:
    - All required skills are present
    - Data fetch before factor computation
    - Factor computation before views
    - Select/allocate after views
    - Backtest before report
    - Coverage check on data failure path
    """
    blockers: List[str] = []
    warnings: List[str] = []
    skill_names = {step.skill_name for step in plan.steps}

    # Required skills present
    missing = _REQUIRED_SKILLS - skill_names
    if missing:
        blockers.append(f"Missing required skills: {sorted(missing)}")

    # Ordering checks
    skill_index: Dict[str, int] = {}
    for i, step in enumerate(plan.steps):
        skill_index[step.skill_name] = i

    ordering_pairs = [
        ("fetch_data", "compute_factors", "Data fetch must precede factor computation"),
        ("compute_factors", "alpha_view", "Factor computation must precede Alpha analysis"),
        ("compute_factors", "risk_evidence_view", "Factor computation must precede Risk & Evidence analysis"),
        ("select_stocks", "allocate_positions", "Stock selection must precede position allocation"),
        ("allocate_positions", "run_backtest", "Position allocation must precede backtest"),
        ("run_backtest", "generate_report", "Backtest must precede report generation"),
        ("fetch_data", "generate_report", "Data fetch must precede report generation"),
    ]

    for before, after, msg in ordering_pairs:
        bi = skill_index.get(before)
        ai = skill_index.get(after)
        if bi is not None and ai is not None and bi >= ai:
            blockers.append(f"Ordering violation: {before} (step {bi}) must come before {after} (step {ai}): {msg}")

    return PlanValidationResult(
        valid=len(blockers) == 0,
        blockers=blockers,
        warnings=warnings,
        missing_required_skills=sorted(missing),
        ordering_violations=[b for b in blockers if "Ordering" in b],
    )


def build_static_quant_plan(query: str = "标准量化投资分析") -> SymphonyPlan:
    """Build a static (non-Symphony) plan for the standard quant workflow.

    This is a FALLBACK used when Symphony API is not available.
    Does not claim "Symphony integration" — use generate_symphony_plan()
    for real Symphony calls.
    """
    contract = get_contract()
    steps = [
        PlanStep(
            step_id="1", skill_name="fetch_data",
            description=(
                f"Fetch daily OHLCV data for all {contract.n_companies} companies "
                "from Sina→Tencent→akshare→baostock→yfinance"
            ),
            depends_on=[], expected_outputs=["price_matrix", "coverage_report"],
        ),
        PlanStep(
            step_id="2", skill_name="compute_factors",
            description="Compute technical factors (momentum_20, momentum_60, reversal_5, max_drawdown, volume_corr, volume_trend)",
            depends_on=["1"], expected_outputs=["factor_scores", "regime_diagnosis"],
        ),
        PlanStep(
            step_id="3", skill_name="alpha_view",
            description="Alpha Analyst: evaluate term-aligned trend, momentum strength, and sector leadership",
            depends_on=["2"], expected_outputs=["alpha_proposals"],
        ),
        PlanStep(
            step_id="4", skill_name="risk_evidence_view",
            description="Risk & Evidence Analyst: evaluate tail risk, max drawdown, divergence, and evidence conflicts",
            depends_on=["2"], expected_outputs=["risk_vetoes"],
        ),
        PlanStep(
            step_id="5", skill_name="select_stocks",
            description="Select top 15 stocks by composite score with sector diversification",
            depends_on=["2"], expected_outputs=["selected_tickers"],
        ),
        PlanStep(
            step_id="6", skill_name="allocate_positions",
            description="Allocate positions: inverse-vol weighting × score tilt, single-stock ≤10%, sector ≤25%",
            depends_on=["5"], expected_outputs=["portfolio_weights"],
        ),
        PlanStep(
            step_id="7", skill_name="run_backtest",
            description="Run open-to-close backtest: first-day open entry, fixed shares, 20-day hold",
            depends_on=["6"], expected_outputs=["backtest_metrics"],
        ),
        PlanStep(
            step_id="8", skill_name="generate_report",
            description=(
                f"Generate {contract.n_companies} per-company reports + "
                "Portfolio.json + resource log + evidence manifest"
            ),
            depends_on=["3", "4", "7"], expected_outputs=["submission_package"],
        ),
    ]

    return SymphonyPlan(
        plan_id=f"static-quant-{datetime.now(timezone.utc).strftime('%Y%m%d-%H%M%S')}",
        query=query,
        generated_at=datetime.now(timezone.utc),
        steps=steps,
        source="static_fallback",
    )
